services:
  db:
    image: postgres:16-alpine
    container_name: smart_dispenser_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smart_dispenser
    ports:
      - "5433:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: smart_dispenser_backend
    restart: always
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/smart_dispenser
      - ESP32_IP=192.168.109.25 # Altere para o IP real se necessário
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: smart_dispenser_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
