services:
  db:
    image: postgres:16-alpine
    container_name: smart_dispenser_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smart_dispenser
    ports:
      - "5433:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d smart_dispenser"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: smart_dispenser_backend
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/smart_dispenser
      - ESP32_IP=192.168.109.25 # Altere para o IP real se necessário
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: smart_dispenser_frontend
    restart: always
    ports:
      - "8082:80"
    depends_on:
      - backend
    profiles:
      - prod

  frontend-dev:
    build:
      context: .
      dockerfile: frontend/Dockerfile.dev
    container_name: smart_dispenser_frontend_dev
    ports:
      - "8081:5173"
    volumes:
      - ./frontend/src:/app/frontend/src
      - ./frontend/public:/app/frontend/public
      - ./frontend/index.html:/app/frontend/index.html
      - ./frontend/vite.config.ts:/app/frontend/vite.config.ts
      - ./frontend/postcss.config.js:/app/frontend/postcss.config.js
      - ./frontend/tailwind.config.js:/app/frontend/tailwind.config.js
      - frontend_node_modules:/app/frontend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://smart_dispenser_backend:8000
      - VITE_HMR_CLIENT_PORT=8081
    depends_on:
      - backend
    profiles:
      - dev

volumes:
  postgres_data:
  frontend_node_modules:
